version: 0.2

phases:
  install:
    java: corretto17
  build:
    commands:
      - mvn clean package -Pprod
  post_build:
    commands:
      -mv target/*.jar ./[your-app-name].jar

artifacts:
  files:
    - [your-app-name].jar