spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #tell spring to run data.sql after tables are created by hibernate
    hibernate:
      ddl-auto: create # specifies how hibernate should interact with existing tables
    show-sql: true
  h2:
    console:
      enabled: true